// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator
// Generator: RgenTemplate (internal)
// Generation date: 2014-01-13 10:35
// Generated by: Win81vm\Admin
// -------------------------------------------------------
namespace RenderersLibraryCS
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.5.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="HelloWorld", Description="HelloWorld", HideInDialog=false)]
    public partial class HelloWorld : Kodeo.Reegenerator.Generators.CodeRenderer
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<returns></returns>
        public override Kodeo.Reegenerator.Generators.RenderResults Render()
        {
            Output.Write("// -------------------------------------------------------\r\n// Automatically gene" +
                    "rated with Kodeo\'s Reegenerator\r\n// Generator: HelloWorld\r\n// Generation date: ");
            Output.Write( System.DateTime.Now.ToString("yyyy-MM-dd hh:mm") );
            Output.Write("\r\n// Generated by: ");
            Output.Write( System.Security.Principal.WindowsIdentity.GetCurrent().Name );
            Output.Write("\r\n// -------------------------------------------------------\r\n\r\n");
 
            Output.Write("\r\n\r\nHello World");
            Output.WriteLine();
            return new Kodeo.Reegenerator.Generators.RenderResults(this.Output.ToString());
        }
    }
}
