// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator
// Generator: XmlToEnum
// Generation date: 2014-01-14 11:31
// Generated by: Win81vm\Admin
// -------------------------------------------------------

partial class SampleClass  {
	enum Days {
		Sat= 1,
		Sun,
		Mon,
		Tue,
		Wed,
		Thu,
		Fri
	}
}
